baseURL = ""
copyright = "Kendal Harland"
languageCode = "en-us"
title = "Oba"
theme = "whisper"
publishDir = "docs"
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true

[params]
  homepage_button_link = "/guides/language/overview/"
  homepage_button_text = "Language Tour"
  homepage_intro = "A lightweight, fast, embeddable, functional scripting language."

[params.logo]
  standard = "/images/logo.png"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Learn"
url = "/guides/language/overview/"
weight = 1

[[menu.main]]
name = "Source"
url =  "https://github.com/oba-lang/oba"
weight = 1

[markup]
  [markup.tableOfContents]
    endLevel = 4
    ordered = false
    startLevel = 2

